CSSS/csss-site

csss-site/src/enVariables/setEnv.sh

adding a script to be able to set env variables from same file that the gunicorn systemd process uses to launch the site

Update env set

---

csss-site/src/csss/templates/csss/header.html

updating code so that the password isn't displayed in plaintext when it is typed in

Hide password

---

csss-site/src/csss/logger_setup.py

fixing logging so that command `python3.7 getmail` can be used with a cronjob.

Fix logging

---

csss-site/src/announcements/templates/announcements/announcements.html

updating the buttons to go to next and previous post to use more human language and adding the line breaks so that the buttons are actually visible.

UI  and word updating to home page

---

CI/Jenkinsfile
CI/deploy_to_prod_server.sh

fixing some typo issues and script to go past folders that can't be deleted because they contain migrations folder

Updating cd

---

CI/Jenkinsfile
CI/deploy_changes.sh
CI/migrate_apps.sh
CI/update_files_on_prod_server.sh
README.md
csss-site/src/csss/settings.py

updating the steps and instructions on how to launch the site locally and also improving CD as a result

Update test steps

---

csss-site/src/administration/election_management.py

when someone wants to change an election, they were unable to because their changes result in the site not being able to locate the election since it would filter for the election based on all the fields and not just the slug.

Fix election bug

---

README.md
csss-site/src/events/templates/events/frosh/frosh_week.html
documentation/add_frosh.md

adding instructions on how to create a frosh page for a new year.

Create frosh instructions

---

csss-site/src/documents/admin.py

renaming parameter to more accurately reflect the context its being used in

rename repo admin parameter

---

csss-site/src/events/views/views.py

forgot to remove the functions linking to the dev frosh pages

removing outdated frosh functions

---

csss-site/src/about/views/import_export_officer_lists.py

fix for bug where the imported listed has only 1 fav language or course

Fix import list bug

---

csss-site/src/about/views/officer_management_helper.py

fixed bug where extra return object caused an error

Fix send email returns

---

csss-site/src/csss/views.py

adding a way to get all the possible valid emails that ever existed to ensure the front page is not empty until a better validation system is implemented that filters out past unrelated emails

adding temp for to get the front page working

---

csss-site/src/about/templates/about/process_new_officer/allow_officer_to_choose_name.html
csss-site/src/about/views/officer_creation_link_management.py

fixing a bug where the user gets a previous officer's profile even when they tried to create a new one

fix bug with officer profile creation link

---

csss-site/src/about/templates/about/process_new_officer/allow_officer_to_choose_name.html
csss-site/src/about/views/officer_creation_link_management.py

fix issue where a previous officer profile was not selected but the code tried to get the previous officer's start date

Fix bug officer select name

---

csss-site/src/resource_management/views/resource_apis/github/github_api.py

fixing bug where a paginated object was treated like a nameduser object

Fix GitHub validation obj

---

csss-site/src/resource_management/views/resource_apis/gdrive/gdrive_api.py

adding more lines of debugging to find out why errors are occurring.

Adding deugging to gdrive api

---

csss-site/src/resource_management/views/resource_apis/gdrive/gdrive_api.py
csss-site/src/resource_management/views/resource_apis/gitlab/gitlab_api.py

code was not previously checking the ownership and permissions for subfolders. this fixes that.

Check folder contents

---

CI/refresh_fixtures/1_update_fixtures.sh
CI/refresh_fixtures/2_create_fixture_jsons.sh
csss-site/src/about/fixtures/about.json
csss-site/src/announcements/fixtures/announcements.json
csss-site/src/resource_management/fixtures/resource_management.json

updating the script to create fixtures as well as the fixtures themselves

updating the fixtures

---

CI/validate_and_deploy/Jenkinsfile
csss-site/src/about/templates/about/list_of_officers.html
csss-site/test/test-requirements.txt

needed to update the `test-requirements` so that the build status would not be `Unstable`

making a change to that Pr can be opened

---

CI/validate_and_deploy/2_deploy/2_deploy_staging_changes.sh

resetting all changes that were made due to refreshing fixtures before checking out PR code

---

csss-site/src/resource_management/views/get_officer_list.py
csss-site/src/resource_management/views/github_views.py
csss-site/src/resource_management/views/resource_apis/github/github_api.py

adding more logging and hopefully fixing issue where some users were removed from teams they were supposed to be in

more logging and github validation issue fixed

---

csss-site/src/resource_management/views/github_views.py
csss-site/src/resource_management/views/resource_apis/github/github_api.py

adding some more logging and a way to ensure that empty teams are not deleted

allow empty teams

---

csss-site/src/resource_management/views/resource_apis/github/github_api.py

allow the creation of empty github teams

Create empty team

---

csss-site/src/about/management/commands/update_officer_images.py

forgot to update the path for the function when updating github workflow

fixing path for function

---

csss-site/src/elections/views/election_management.py
csss-site/src/elections/views/election_management_helper.py

applying temporary election app fixes as the election will happen before the revamp is complete

temp election fixes

---

csss-site/src/elections/views/election_management.py
csss-site/src/elections/views/election_management_helper.py

Revert "temp election fixes"

---

csss-site/src/elections/views/election_management.py
csss-site/src/elections/views/election_management_helper.py

Revert "applying temporary election app fixes as the election will happen bef…"

---

csss-site/src/csss/static/csss_static/csss_markdown.css
csss-site/src/csss/templates/csss/markdown_preview.html
csss-site/src/csss/views.py

(cherry picked from commit 64bd22843a0da893ead543f45fe425a297ece15b)

fixing issue with having code blocks intermixed with paragraphs

---

csss-site/src/about/views/officer_position_and_github_mapping/update_saved_position_mappings.py
csss-site/src/csss/views_helper.py

make sure that changing a position's name or index can be properly reflected on current officers and elections in current term

Position changed effect elections

---

csss-site/src/elections/templates/elections/webform/form__webform.html

adding submission button and add another nominee below nominees so user does not have to continously scroll up to add nominee and scroll down again to modify the nominee

update webform button placement

---

CI/validate_and_deploy/2_deploy/1_update_files_on_master_server.sh
CI/validate_and_deploy/2_deploy/2_deploy_master_changes.sh

moving the steps to an earlier script since the scp commands are the ones that take the most amount of time

 change when construction page is setup

---

CI/nginx_conf_files/1_nginx_config_file
CI/nginx_conf_files/2_nginx_config_file
csss-site/src/about/management/commands/update_officer_images.py
csss-site/src/announcements/management/commands/create_attachments.py
csss-site/src/csss/management/commands/setup_website.py
csss-site/src/csss/settings.py

updating nginx so that one rule is needed for all the assets and making necessary accomodations to the django commands to work with the new layout

updating nginx so one rule is needed for all assets

---

csss-site/src/elections/views/utils/transform_webform_to_json.py
csss-site/src/elections/views/validators/validate_speech_and_position_names.py

updating transform to not include the ID if its not a number and updating validation to just delete the ID if its invalid

removing invalid speech IDs

---

CI/fixtures_and_media_download/create_dockerized_database_with_migration.sh

fixing script so that the staging server does not download the migrations from itself

update Staging fixture CI/CD

---

csss-site/src/csss/views_helper.py
csss-site/src/elections/templates/elections/election_page.html
csss-site/src/elections/views/endpoints/election_page.py
csss-site/src/resource_management/views/gdrive_views.py

moving the ERROR_MESSAGE_KEY to the google drive view as that is the only place its used

Re factor error message key

---

csss-site/src/about/models.py

fixing validation to ensure that existing officers are not matched against themselves

Fix officer validation

---

csss-site/src/events/fall_hacks/templates/fall_hacks/2020/fall_hacks_submissions2020.html
csss-site/src/events/mountain_madness/static/mountain_madness_static/2021/csss_custom.css
csss-site/src/events/mountain_madness/static/mountain_madness_static/2021/mm2021_main.css
csss-site/src/events/mountain_madness/templates/mountain_madness/2021/mountain_madness2021.html
csss-site/src/events/mountain_madness/templates/mountain_madness/2021/mountain_madness2021_submissions.html
csss-site/src/events/mountain_madness/urls.py
csss-site/src/events/mountain_madness/views.py

Added page linked within Mountain Madness 2021 page to submissions.

Added page for Mountain Madness 2021 submissions

---

csss-site/src/events/frosh/templates/frosh/2022/frosh.html

- Adjusted CS Info Session time and location
- Confirmed location for Pac Macro, Thursday Dinner, and Midnight Madness start
- Fixed a grammatical mistake
- Adjusted Google Calendar to use updated times/locations

Confirm all outstanding event times and locations

---

csss-site/src/about/management/commands/validate_discord_roles_members.py
csss-site/src/csss/views_helper.py

Adding logic where the exec-at-larges from previous term will be given the discord role if there has not been a GM yet where new exec-at-larges can been elected.

Allow exec at large from previous term

---

csss-site/src/static_pages/templates/static_pages/bursaries.html

Scholarship in question: Maliha & Amina Bai Ropani Memorial Scholarship (inquired by Nancy to remove).

Remove a scholarship that is not offered anymore.

---

csss-site/src/events/frosh/templates/frosh/2013/header.html
csss-site/src/events/frosh/templates/frosh/2013/index.html
csss-site/src/events/frosh/templates/frosh/2014/index.html
csss-site/src/events/frosh/templates/frosh/2015/frosh.html
csss-site/src/events/frosh/templates/frosh/2016/frosh.html
csss-site/src/events/frosh/templates/frosh/2017/frosh.html
csss-site/src/events/frosh/templates/frosh/2018/frosh.html

Converted `<br />` and `<br/>` to `<br>`.

Fixing extra character in br statement

---

csss-site/src/about/templates/about/who_we_are.html

Added information about FAS Formal, Silicon Valley trip, Tech fair to the `who we are` page.

Updating static details

---

csss-site/src/csss/templates/csss/header.html

Updating instagram link

---

csss-site/src/elections/models.py
csss-site/src/elections/views/endpoints/nominee_links/display_and_process_html_for_nominee_modification_via_passphrase__nominee_link.py
csss-site/src/elections/views/extractors/get_election_nominees.py
csss-site/src/elections/views/save_election/save_new_election_and_nominee_links.py
csss-site/src/elections/views/save_election/save_new_nominee_links_from_jformat.py
csss-site/src/elections/views/save_election/update_existing_nominee_links_from_jformat.py
csss-site/src/elections/views/save_nominee/save_new_nominee_jformat.py
csss-site/src/elections/views/save_nominee/update_existing_nominees_jformat.py
csss-site/src/elections/views/update_election/nominee_links/process_nominee__nominee_links.py
csss-site/src/elections/views/utils/webform_to_json/nominee_links/transform_nominee_links_webform_to_json.py
csss-site/src/elections/views/validators/validate_existing_nominee_jformat.py
csss-site/src/elections/views/validators/validate_existing_nominees__nominee_link.py
csss-site/src/elections/views/validators/validate_info_for_nominee_obj.py

switching validation so the value is always saved as NA_STRING but then converted to None in the Save function

setting NA to None on save() for Nominee and NomineeLink objects

---

CI/validate_and_deploy/Jenkinsfile

fixing interpolation so our sensitive variables do not get leaked https://www.jenkins.io/doc/book/pipeline/jenkinsfile/#string-interpolation

Fix interpolation of sensitive enviroment variables

---

csss-site/src/events/tech_fair/static/tech_fair/2023/css/tech_fair.css
csss-site/src/events/tech_fair/templates/tech_fair/2023/tech_fair.html
csss-site/src/events/tech_fair/templates/tech_fair/2023/tech_fair_company_package.html

Tech Fair's dates have been changed (from sept 27 & 28 to just oct 25) and so the frontend must be modified to reflect that.
@modernNeo This PR is complete, however I've set this as a draft so that we do not accidentally merge these changes until the Tech Fair Committee gets a space confirmation for the new date (expected less than 1 week). I'll set you as reviewer once I get a confirmation from them.

Tech Fair 2023 - Update Date

---

csss-site/src/events/tech_fair/static/tech_fair/2023/css/main.css
csss-site/src/events/tech_fair/templates/tech_fair/2023/tech_fair.html
csss-site/src/events/tech_fair/templates/tech_fair/2023/tech_fair_company_package.html

I was asked to make the mobile version of the tech fair site usable!

Fix mobile site for 2023 Tech Fair

---

csss-site/src/csss/setup_logger.py

adding logic to cut down on how much loging is kept

implement-rotating-logs
